/*
 * Copyright (C) 2025 Parisi Alessandro - alessandro.parisi406@gmail.com
 * This file is part of MaterialFX (https://github.com/palexdev/MaterialFX)
 *
 * MaterialFX is free software: you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public License
 * as published by the Free Software Foundation; either version 3 of the License,
 * or (at your option) any later version.
 *
 * MaterialFX is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with MaterialFX. If not, see <http://www.gnu.org/licenses/>.
 */

plugins {
    id 'java-library'
    id 'org.openjfx.javafxplugin' version "$jfxPlugin" apply false
    id 'org.beryx.jlink' version "$jlink" apply false
    id 'com.vanniktech.maven.publish' version "$mavenPublishPlugin" apply false
}

ext {
    scriptsDir = "$rootDir/gradle"
}

subprojects {
    apply plugin: "java-library"
    apply plugin: "org.openjfx.javafxplugin"
    apply plugin: "com.vanniktech.maven.publish"

    // Remove vanniktech nonsense
    gradle.taskGraph.whenReady { graph ->
        if (graph.hasTask(plainJavadocJar)) {
            plainJavadocJar.enabled = false
        }
    }

    group 'io.github.palexdev'

    repositories {
        mavenLocal()
        mavenCentral()
    }

    dependencies {
        testImplementation platform("org.junit:junit-bom:$junit")
        testImplementation 'org.junit.jupiter:junit-jupiter'
        testRuntimeOnly "org.junit.platform:junit-platform-launcher"
        testImplementation "org.hamcrest:hamcrest:$hamcrest"
        testImplementation "org.testfx:testfx-junit5:$testfx"
        testImplementation("io.github.palexdev:scenicview:$scenicView") {
            exclude group: "org.openjfx"
        }
        testImplementation "one.jpro.platform.jpms:cssfx:$cssfx"
    }

    javafx {
        version = "$jfx"
        modules = ["javafx.controls", "javafx.fxml"]
        configurations = ['compileOnly', 'testImplementation']
    }

    compileJava {
        sourceCompatibility = "$jdk"
        targetCompatibility = "$jdk"
    }

    test {
        useJUnitPlatform()
        // FIXME well, this depends on the Gradle team if they decide to revert a dumb decision
        failOnNoDiscoveredTests = false

        jvmArgs += ['--enable-native-access=ALL-UNNAMED']
        systemProperty 'glass.platform', 'headless'
        systemProperty 'prism.order', 'sw'
    }
}



