#
# Copyright (C) 2025 Parisi Alessandro - alessandro.parisi406@gmail.com
# This file is part of MaterialFX (https://github.com/palexdev/MaterialFX)
#
# MaterialFX is free software: you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public License
# as published by the Free Software Foundation; either version 3 of the License,
# or (at your option) any later version.
#
# MaterialFX is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with MaterialFX. If not, see <http://www.gnu.org/licenses/>.
#

#@formatter:off
#--------------------------------------#
# Maven                                #
#--------------------------------------#
GROUP=io.github.palexdev

POM_URL=https://github.com/palexdev/MaterialFX
POM_SCM_URL=https://github.com/palexdev/MaterialFX

POM_DEVELOPER_ID=palexdev
POM_DEVELOPER_NAME=Alessandro Parisi
POM_DEVELOPER_URL=https://github.com/palexdev

POM_PACKAGING=jar

#--------------------------------------#
# Versions                             #
#--------------------------------------#
jdk=25

# Plugins
jfxPlugin=0.1.0
jlink=3.1.1
mavenPublishPlugin=0.34.0
gradleSass=1.5.2
shadowJarPlugin=9.0.0-beta15

# Dependencies
jfx=26
vfx=25.1.0
sass=1.89.1

# Test Dependencies
junit=5.13.0
hamcrest=3.0
testfx=4.0.18
scenicView=17.0.2
ikonli=12.4.0
cssfx=11+