import groovy.transform.Field
import org.apache.tools.ant.taskdefs.condition.Os

import java.nio.file.Files

// Special handling for Windows. Fuck. This. Shit.
@Field var isWindows = (Os.isFamily(Os.FAMILY_WINDOWS))

tasks.register("processCSS") {
    doLast {
        def rootDir = rootProject.projectDir.absolutePath
        def resDir = new File("$rootDir/modules/resources/src/main/resources/io/github/palexdev/mfxresources/sass/themes")
        def files = Files.walk(resDir.toPath())
                .filter(p -> {
                    def name = p.getFileName().toString()
                    return !Files.isDirectory(p) && name.endsWith(".css") && !name.startsWith("tmp") && !name.contains("preset")
                }).toList()
        if (files.isEmpty()) return

        // Check if npm, cleancss-cli and cssbeautify-cli are installed on the host
        if (!execute(["npm", "-v"])) {
            logger.error("npm command could not be found")
            return
        }
        if (!execute(["cleancss", "-v"])) {
            logger.error("cleancss command could not be found")
            return
        }
        if (!execute(["cssbeautify-cli", "-v"])) {
            logger.error("cssbeautify-cli command could not be found")
            return
        }
        logger.info("All dependencies have been found")

        files.each {
            def name = it.getFileName().toString()
            def parent = it.getParent().toAbsolutePath()
            def tmp = new File("${parent}/tmp.css")

            logger.lifecycle("Optimizing: $name")
            execute([
                    "cleancss",
                    "-O2", "specialComments:all",
                    "--format", "beautify",
                    "--inline", "none",
                    "${it}" as String,
                    "-o", "${tmp}" as String
            ], parent.toFile())

            logger.lifecycle("Beautifying: $name")
            execute([
                    "cssbeautify-cli",
                    "-i2",
                    "-f", "${tmp}" as String,
                    "-w", "${it}" as String
            ], parent.toFile())

            delete(tmp)
        }
    }
}

boolean execute(List<String> cmd, File workDir = null) {
    if (isWindows) cmd.addAll(0, "cmd", "/c") // Prepend call to cmd
    try {
        Process proc = new ProcessBuilder(cmd)
                .directory(workDir)
                .start()
        proc.waitForOrKill(10_000)
        return proc.exitValue() == 0
    } catch (Throwable e) {
        logger.error(e.getMessage())
        return -1
    }
}