version = "$components"

dependencies {
    api(project(":core"))
    api(project(':effects'))
    api(project(":localization"))
    api(project(":resources"))
    api "io.github.palexdev:material-color-utilities:$mcu"
    api("io.github.palexdev:virtualizedfx:$vfx") {
        exclude group: 'io.github.palexdev'
    }
}

java {
    withSourcesJar()
    withJavadocJar()
    tasks.withType(Jar).each { it.archiveBaseName.set("components") }
}

tasks.register('testRun', JavaExec) {
    classpath = sourceSets.test.runtimeClasspath
    mainClass.set(provider {
        if (project.hasProperty("mainClass")) {
            return "apps." + project.getProperty("mainClass")
        } else {
            throw new GradleException("Cannot run task without mainClass argument")
        }
    })
}

mavenPublishing {
    publishToMavenCentral()
    signAllPublications()
}