/*
 * Copyright (C) 2025 Parisi Alessandro - alessandro.parisi406@gmail.com
 * This file is part of MaterialFX (https://github.com/palexdev/MaterialFX)
 *
 * MaterialFX is free software: you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public License
 * as published by the Free Software Foundation; either version 3 of the License,
 * or (at your option) any later version.
 *
 * MaterialFX is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with MaterialFX. If not, see <http://www.gnu.org/licenses/>.
 */

package io.github.palexdev.mfxeffects.enums;

import java.util.Arrays;

import io.github.palexdev.mfxeffects.animations.Animations.KeyFrames;
import io.github.palexdev.mfxeffects.animations.Animations.TimelineBuilder;
import io.github.palexdev.mfxeffects.animations.motion.M3Motion;
import javafx.animation.Animation;
import javafx.scene.effect.BlurType;
import javafx.scene.effect.DropShadow;
import javafx.scene.paint.Color;

/// Enumerator which defines 6 levels of `DropShadow` effects from `LEVEL0` to `LEVEL5`.
public enum ElevationLevel {
    // 0dp
    LEVEL0(0, 0, 0, 0),

    // 1dp
    LEVEL1(3, 0.12, 0, 2),

    // 3dp
    LEVEL2(8, 0.16, 0, 3),

    // 6dp
    LEVEL3(18, 0.19, 0, 3),

    // 8dp
    LEVEL4(14, 0.25, 0, 5),

    // 12dp
    LEVEL5(16, 0.30, 0, 7);

    private final Color color;
    private final double radius;
    private final double spread;
    private final double offsetX;
    private final double offsetY;

    ElevationLevel(double radius, double spread, double offsetX, double offsetY) {
        this.color = Color.rgb(0, 0, 0, 0.20);
        this.radius = radius;
        this.spread = spread;
        this.offsetX = offsetX;
        this.offsetY = offsetY;
    }

    public Color getColor() {
        return color;
    }

    public double getRadius() {
        return radius;
    }

    public double getSpread() {
        return spread;
    }

    public double getOffsetX() {
        return offsetX;
    }

    public double getOffsetY() {
        return offsetY;
    }

    /// Retrieves the next `DepthLevel` associated with `this` enumerator.
    ///
    /// @return The next `DepthLevel`
    public ElevationLevel next() {
        return values()[(this.ordinal() + 1) % values().length];
    }

    public DropShadow toShadow() {
        return new DropShadow(
            BlurType.GAUSSIAN, getColor(),
            getRadius(), getSpread(),
            getOffsetX(), getOffsetY()
        );
    }

    public static Animation animation(DropShadow current, ElevationLevel next) {
        M3Motion.MotionPreset m = M3Motion.EXPRESSIVE_SLOW_EFFECTS;
        return TimelineBuilder.build()
            .add(KeyFrames.of(1, current.offsetXProperty(), next.getOffsetX(), m.curve()))
            .add(KeyFrames.of(1, current.offsetYProperty(), next.getOffsetY(), m.curve()))
            .add(KeyFrames.of(m.duration(), current.radiusProperty(), next.getRadius(), m.curve()))
            .add(KeyFrames.of(m.duration(), current.spreadProperty(), next.getSpread(), m.curve()))
            .getAnimation();
    }

    /// Attempts to get the corresponding `DepthLevel` of the given [DropShadow] effect.
    /// If the given effect is not recognized as being generated by this class, the `null` is returned.
    ///
    /// Uses [#levelEqualsShadow(ElevationLevel,DropShadow)] to check for equality.
    public static ElevationLevel from(DropShadow shadow) {
        return Arrays.stream(values()).filter(depthLevel -> levelEqualsShadow(depthLevel, shadow))
            .findFirst()
            .orElse(null);
    }

    /// Checks if the given [DropShadow] effect is equal to the given `DepthLevel`.
    public static boolean levelEqualsShadow(ElevationLevel level, DropShadow shadow) {
        return level.color.equals(shadow.getColor()) &&
               level.offsetX == shadow.getOffsetX() &&
               level.offsetY == shadow.getOffsetY() &&
               level.radius == shadow.getRadius() &&
               level.spread == shadow.getSpread();
    }
}
