/*
 * Copyright (C) 2026 Parisi Alessandro - alessandro.parisi406@gmail.com
 * This file is part of MaterialFX (https://github.com/palexdev/MaterialFX)
 *
 * MaterialFX is free software: you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public License
 * as published by the Free Software Foundation; either version 3 of the License,
 * or (at your option) any later version.
 *
 * MaterialFX is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with MaterialFX. If not, see <http://www.gnu.org/licenses/>.
 */

package io.github.palexdev.mfxresources.icon;

import java.util.List;
import java.util.function.BiFunction;
import java.util.function.Function;

import io.github.palexdev.mfxeffects.beans.Position;
import io.github.palexdev.mfxeffects.ripple.MFXRippleGenerator;
import io.github.palexdev.mfxeffects.ripple.base.RippleGenerator;
import io.github.palexdev.mfxeffects.utils.StyleUtils;
import io.github.palexdev.mfxresources.icon.IconClip.IconClipConverter;
import javafx.collections.ObservableList;
import javafx.css.*;
import javafx.geometry.HPos;
import javafx.geometry.VPos;
import javafx.scene.Node;
import javafx.scene.input.MouseButton;
import javafx.scene.input.MouseEvent;
import javafx.scene.layout.Region;

/// This component is a wrapper for [MFXFontIcon]s and offers many related features and conveniences such as:
///  - An optional ripple effect on click, generated by a [MFXRippleGenerator], see [#enableRipple(boolean)].
///  - Quickly clip the container to the desired shape and even from CSS, see [#iconClipProperty()] and [IconClip].
///  - Switching icons with animations. There are many modern and beautiful prebuilt in [AnimationPresets].
///
/// They can also be set from CSS, see [#animationPresetProperty()].
///
/// ### Sizing
/// By design, the wrapper is a squared region. By default, its size is the maximum between the icon's width and height,
/// including padding. There's also the [#sizeProperty()] which acts as a minimum. In other words, the effective size
/// of the wrapper is the maximum between three values: the icon's width and height (including horizontal and vertical padding
/// respectively) and this value (no padding). This system should offer enough flexibility to the user. The computation is
/// handled by [#computeSize()].
///
/// ### Animations
/// The wrapper is capable of switching icons through an animation, even when the [#iconProperty()] is bound.
/// The API has been developed to be as flexible as possible while still following some critical rules, and with some compromises.
///
/// The animation is built by a [BiFunction] which accepts both the current and new icons and Can be set from two ways:
/// by using [#setAnimationProvider(BiFunction)] or by using a preset from [AnimationPresets].
///
/// The [IconAnimation] class carries the animation because there are extra steps happening behind the scenes.
/// Initially, the wrapper was intended to contain at most two nodes: the icon and the ripple generator. To introduce animations,
/// we must allow for the current and new icon to coexist for a certain period of time. To not break encapsulation by giving
/// the modifiable children's list to the user, I hid some code in the aforementioned class. When the animation stops
/// (either because interrupted or finished), the old icon is automatically removed from the wrapper. This way we ensure that
/// this is always in a consistent state.
///
/// Two more important details:
///  1) When the new icon is added to the wrapper, it is set to be invisible to allow animations needing it to initialize
/// the node before they play
///  2) Any initialization/change made by the animation to the new icon **must** be properly reset by its author when
/// the animation stops. You can inline override [IconAnimation#onStopped(MFXIconWrapper)] and add the reset code there.
/// So, for example, if an animation is changing the opacity of the new icon, and it is stopped for whatever reason, the author
/// should take this into account and add the proper reset code.
///
/// The animation is controlled by the [#animate(MFXFontIcon, MFXFontIcon)] method. The whole mechanism can be disabled
/// by setting the [#animatedProperty()] to `false`.
///
/// ### CSS vs. Code
/// Last but not least, it's worth mentioning that some CSS-related methods are just a bridge for other methods.
/// They simply allow some functionalities to be customized without the need of the wrapper's instance.
///
/// For example, the [#animationPresetProperty()] is a bridge that calls [#setAnimationProvider(BiFunction)].
///
/// Other properties that follow the same logic are: [#iconNameProperty()], [#enableRippleProperty()],
/// [#iconClipProperty()].
///
/// If you use both the bridge and the "standard" method, the CSS properties end up being "desynchronized".
/// It should not be an issue, but I advise against it.
public class MFXIconWrapper extends Region {
    //================================================================================
    // Properties
    //================================================================================
    // Icon
    protected boolean preserveClip = false;
    protected MFXFontIcon _icon;
    private final IconProperty icon = new IconProperty() {
        @Override
        protected void invalidated() {
            MFXFontIcon oldIcon = _icon;
            if (isAnimated()) {
                animate(oldIcon, get());
            } else {
                updateChildren();
            }
        }
    };

    // Animation
    private IconAnimation animation;
    private BiFunction<MFXFontIcon, MFXFontIcon, IconAnimation> animationProvider;

    // Ripple
    private MFXRippleGenerator rg;

    //================================================================================
    // Constructors
    //================================================================================
    public MFXIconWrapper() {
        this(new MFXFontIcon(), -1.0);
    }

    public MFXIconWrapper(MFXFontIcon icon) {
        this(icon, -1.0);
    }

    public MFXIconWrapper(MFXFontIcon icon, double size) {
        setSize(size);
        setIcon(icon);
    }

    {
        getStyleClass().add("mfx-icon-wrapper");
        setMinSize(USE_PREF_SIZE, USE_PREF_SIZE);
        setMaxSize(USE_PREF_SIZE, USE_PREF_SIZE);
        addEventHandler(MouseEvent.MOUSE_PRESSED, _ -> requestFocus());
    }

    //================================================================================
    // Methods
    //================================================================================

    /// Delegates to [#enableRipple(boolean, Function)] with a function that returns a `null` position if the
    /// pressed button is not [MouseButton#PRIMARY].
    public MFXIconWrapper enableRipple(boolean enable) {
        return enableRipple(enable, me ->
            (me.getButton() == MouseButton.PRIMARY) ? Position.of(me.getX(), me.getY()) : null
        );
    }

    /// Enables or disables the ripple generator.
    ///
    /// When disabled, the generator is disposed, removed from the children's list and set to `null`. On the contrary,
    /// when enabled, a new one is created and enabled in this region ([RippleGenerator#enable()]).
    ///
    /// @see MFXRippleGenerator#setMeToPosConverter(Function)
    public MFXIconWrapper enableRipple(boolean enable, Function<MouseEvent, Position> posFn) {
        if (!enable && rg != null) {
            rg.dispose();
            getChildren().remove(rg);
            rg = null;
        } else if (enable && rg == null) {
            rg = new MFXRippleGenerator(this);
            rg.setMeToPosConverter(posFn);
            getChildren().add(rg);
            rg.enable();
        }
        return this;
    }

    /// This is invoked when the [#iconProperty()] becomes invalid, but only if the [#animatedProperty()] is `true`.
    ///
    /// There are also conditions leading to the animation not being played, such as the current icon or the new icon
    /// being `null`; the region is disabled. In such cases, it falls back to [#updateChildren()].
    ///
    /// If there's already an animation playing, it is stopped by calling [IconAnimation#stop()]. Then the new icon
    /// is set to be invisible and added to the children's list. A new animation is built by the animation provider and played
    /// using [IconAnimation#play(MFXIconWrapper)].
    ///
    /// @throws IllegalStateException if the icon is animated but no animation provider was set. Falls back to
    /// [#updateChildren()]
    protected void animate(MFXFontIcon oldIcon, MFXFontIcon newIcon) {
        if (oldIcon == null ||
            newIcon == null ||
            isDisabled()
        ) {
            updateChildren();
            return;
        }

        if (animationProvider == null) {
            updateChildren();
            throw new IllegalStateException("The icon wrapper is set to be animated but no animation provider was set");
        }

        if (animation != null)
            animation.stop();

        newIcon.setVisible(false);
        newIcon.setMouseTransparent(true);
        newIcon.setViewOrder(1);
        getChildren().add(newIcon);
        animation = animationProvider.apply(oldIcon, newIcon);
        animation.play(this);
        _icon = newIcon;
    }

    /// This is invoked when either the [#iconProperty()] becomes invalid or if [#animate(MFXFontIcon, MFXFontIcon)]
    /// cannot proceed.
    ///
    /// Simply removes the current icon and adds the new one to the children's list.
    protected void updateChildren() {
        MFXFontIcon icon = getIcon();
        if (_icon != null) getChildren().remove(_icon);
        if (icon != null) {
            icon.setViewOrder(1);
            icon.setMouseTransparent(true);
            getChildren().add(icon);
        }
        _icon = icon;
    }

    /// This is invoked when the [#iconClipProperty()] becomes invalid. If the new value is `null`, then the
    /// clip is removed. Otherwise, the clip node is built by [IconClip#build(Region)] according to the chosen shape
    /// and set on the region.
    protected void updateClip() {
        IconClip ic = getIconClip();
        if (ic == null) {
            setClip(null);
            return;
        }
        Node clip = ic.build(this);
        setClip(clip);
    }

    /// This is responsible for computing the wrapper's size, which will be both its width and height.
    ///
    /// If the icon is `null`, it returns `0.0` or [#sizeProperty()] if positive.
    ///
    /// Otherwise, it returns the maximum between two values: the icon's size, including horizontal and
    /// vertical padding, and the value of [#sizeProperty()].
    ///
    /// The [#sizeProperty()] acts as a minimum. To make the region squared, both its minimum and maximum sizes are
    /// overridden to use the pref which delegates the computation to this method.
    ///
    /// **Warning:**
    ///
    /// As stated above, we use [MFXFontIcon#sizeProperty()] and not the actual rendered width and height.<br >
    /// Font rendering is complicated and not reliable. Using the rendered sizes may lead to the wrapper
    /// growing or shrinking depending on the icon. This way is not perfect and still depends on the icon pack, but it
    /// should be more stable.
    protected double computeSize() {
        MFXFontIcon icon = getIcon();
        double size = getSize();
        if (icon == null) return Math.max(0.0, size);

        double iw = snappedLeftInset() + icon.getSize() + snappedRightInset();
        double ih = snappedTopInset() + icon.getSize() + snappedBottomInset();
        return Math.max(size, Math.max(iw, ih));
    }

    /// @return the wrapper's size by calling [#prefWidth(double)]. It could also call [#prefHeight(double)], but it does
    /// not matter since both are overridden to call [#computeSize()]. So, effectively, this is a shortcut to the latter,
    /// but we take advantage of JavaFX caching and do not compute the value every time.
    public double prefSize() {
        return prefWidth(-1);
    }

    @Override
    protected ObservableList<Node> getChildren() {
        return super.getChildren();
    }

    //================================================================================
    // Overridden Methods
    //================================================================================

    /// Delegates to [#computeSize()].
    @Override
    protected double computePrefWidth(double height) {
        return computeSize();
    }

    /// Delegates to [#computeSize()].
    @Override
    protected double computePrefHeight(double width) {
        return computeSize();
    }

    @Override
    protected void layoutChildren() {
        for (Node child : getChildren()) {
            layoutInArea(child, 0, 0, getWidth(), getHeight(), 0, HPos.CENTER, VPos.CENTER);
        }
    }

    //================================================================================
    // Styleable Properties
    //================================================================================
    private final StyleableBooleanProperty animated = new SimpleStyleableBooleanProperty(
        StyleableProperties.ANIMATED,
        this,
        "animated",
        false
    ) {
        @Override
        public StyleOrigin getStyleOrigin() {
            return StyleOrigin.USER_AGENT;
        }
    };

    private final StyleableObjectProperty<AnimationPresets> animationPreset = new SimpleStyleableObjectProperty<>(
        StyleableProperties.ANIMATION_PRESET,
        this,
        "animationPreset",
        null
    ) {
        @Override
        protected void invalidated() {
            AnimationPresets ap = get();
            if (ap != null) setAnimationProvider(ap);
        }

        @Override
        public StyleOrigin getStyleOrigin() {
            return StyleOrigin.USER_AGENT;
        }
    };

    private final StyleableDoubleProperty size = new SimpleStyleableDoubleProperty(
        StyleableProperties.SIZE,
        this,
        "size",
        -1.0
    ) {
        @Override
        protected void invalidated() {
            requestLayout();
        }

        @Override
        public StyleOrigin getStyleOrigin() {
            return StyleOrigin.USER_AGENT;
        }
    };

    private final StyleableStringProperty iconName = new SimpleStyleableStringProperty(
        StyleableProperties.ICON_NAME,
        this,
        "iconName",
        ""
    ) {
        @Override
        protected void invalidated() {
            if (!icon.isBound())
                setIcon(get());
        }

        @Override
        public StyleOrigin getStyleOrigin() {
            return StyleOrigin.USER_AGENT;
        }
    };

    private final StyleableBooleanProperty enableRipple = new SimpleStyleableBooleanProperty(
        StyleableProperties.ENABLE_RIPPLE,
        this,
        "enableRipple",
        false
    ) {
        @Override
        protected void invalidated() {
            enableRipple(get());
        }

        @Override
        public StyleOrigin getStyleOrigin() {
            return StyleOrigin.USER_AGENT;
        }
    };

    private final StyleableObjectProperty<IconClip> iconClip = new SimpleStyleableObjectProperty<>(
        StyleableProperties.ICON_CLIP,
        this,
        "iconClip",
        null
    ) {
        @Override
        protected void invalidated() {
            updateClip();
        }

        @Override
        public StyleOrigin getStyleOrigin() {
            return StyleOrigin.USER_AGENT;
        }
    };

    public boolean isAnimated() {
        return animated.get();
    }

    /// Specifies whether to play an animation when the wrapper's icon changes.
    ///
    /// Can be set from CSS via the property: '-mfx-animated'.
    public StyleableBooleanProperty animatedProperty() {
        return animated;
    }

    public MFXIconWrapper setAnimated(boolean animated) {
        this.animated.set(animated);
        return this;
    }

    public AnimationPresets getAnimationPreset() {
        return animationPreset.get();
    }

    /// A convenient bridge that allows setting the wrapper's animation when switching icons from CSS via the property:
    /// '-mfx-animation'.
    public StyleableObjectProperty<AnimationPresets> animationPresetProperty() {
        return animationPreset;
    }

    public MFXIconWrapper setAnimationPreset(AnimationPresets animationPreset) {
        this.animationPreset.set(animationPreset);
        return this;
    }

    public double getSize() {
        return size.get();
    }

    /// Specifies the minimum width and height of the wrapper.
    ///
    /// Can be set from CSS via the property: '-mfx-size'.
    public StyleableDoubleProperty sizeProperty() {
        return size;
    }

    public MFXIconWrapper setSize(double size) {
        this.size.set(size);
        return this;
    }

    public String getIconName() {
        return iconName.get();
    }

    /// A convenient bridge that allows to change the wrapper's icon from CSS and trigger the animation if possible, via the property:
    /// '-mfx-icon'.
    public StyleableStringProperty iconNameProperty() {
        return iconName;
    }

    public MFXIconWrapper setIconName(String iconName) {
        this.iconName.set(iconName);
        return this;
    }

    public boolean isEnableRipple() {
        return enableRipple.get();
    }

    /// A convenient bridge that allows to enable ripple effects from CSS via the property:
    /// '-mfx-enable-ripple'.
    public StyleableBooleanProperty enableRippleProperty() {
        return enableRipple;
    }

    public MFXIconWrapper setEnableRipple(boolean enableRipple) {
        this.enableRipple.set(enableRipple);
        return this;
    }

    public IconClip getIconClip() {
        return iconClip.get();
    }

    /// A convenient bridge that allows to clip the wrapper from CSS via the property:
    /// '-mfx-clip'.
    public StyleableObjectProperty<IconClip> iconClipProperty() {
        return iconClip;
    }

    public MFXIconWrapper setIconClip(IconClip iconClip) {
        this.iconClip.set(iconClip);
        return this;
    }

    //================================================================================
    // CssMetaData
    //================================================================================
    private static class StyleableProperties {
        private static final StyleablePropertyFactory<MFXIconWrapper> FACTORY = new StyleablePropertyFactory<>(Region.getClassCssMetaData());
        private static final List<CssMetaData<? extends Styleable, ?>> cssMetaDataList;

        private static final CssMetaData<MFXIconWrapper, Boolean> ANIMATED =
            FACTORY.createBooleanCssMetaData(
                "-mfx-animated",
                MFXIconWrapper::animatedProperty,
                false
            );

        private static final CssMetaData<MFXIconWrapper, AnimationPresets> ANIMATION_PRESET =
            FACTORY.createEnumCssMetaData(
                AnimationPresets.class,
                "-mfx-animation",
                MFXIconWrapper::animationPresetProperty,
                null
            );

        private static final CssMetaData<MFXIconWrapper, Number> SIZE =
            FACTORY.createSizeCssMetaData(
                "-mfx-size",
                MFXIconWrapper::sizeProperty,
                -1.0
            );

        private static final CssMetaData<MFXIconWrapper, String> ICON_NAME =
            FACTORY.createStringCssMetaData(
                "-mfx-icon",
                MFXIconWrapper::iconNameProperty,
                ""
            );

        private static final CssMetaData<MFXIconWrapper, Boolean> ENABLE_RIPPLE =
            FACTORY.createBooleanCssMetaData(
                "-mfx-enable-ripple",
                MFXIconWrapper::enableRippleProperty,
                false
            );

        private static final CssMetaData<MFXIconWrapper, IconClip> ICON_CLIP = new CssMetaData<>(
            "-mfx-clip", IconClipConverter.instance(), null
        ) {
            @Override
            public StyleableProperty<IconClip> getStyleableProperty(MFXIconWrapper styleable) {
                return styleable.iconClipProperty();
            }

            @Override
            public boolean isSettable(MFXIconWrapper styleable) {
                return !styleable.iconClipProperty().isBound();
            }
        };

        static {
            cssMetaDataList = StyleUtils.cssMetaDataList(
                Region.getClassCssMetaData(),
                ANIMATED, ANIMATION_PRESET, SIZE, ICON_NAME, ENABLE_RIPPLE, ICON_CLIP
            );
        }
    }

    public static List<CssMetaData<? extends Styleable, ?>> getClassCssMetaData() {
        return StyleableProperties.cssMetaDataList;
    }

    @Override
    public List<CssMetaData<? extends Styleable, ?>> getCssMetaData() {
        return getClassCssMetaData();
    }

    //================================================================================
    // Getters/Setters
    //================================================================================

    public MFXFontIcon getIcon() {
        return icon.get();
    }

    /// Specifies the currently contained [MFXFontIcon].
    public IconProperty iconProperty() {
        return icon;
    }

    public MFXIconWrapper setIcon(MFXFontIcon icon) {
        this.icon.set(icon);
        return this;
    }

    /// Convenience method to set the [#iconProperty()] to a new [MFXFontIcon] instance given a font icon name.
    public MFXIconWrapper setIcon(String iconName) {
        icon.setIcon(iconName);
        return this;
    }

    /// @see #setAnimationProvider(BiFunction)
    public BiFunction<MFXFontIcon, MFXFontIcon, IconAnimation> getAnimationProvider() {
        return animationProvider;
    }

    /// Sets the function responsible for building the animation to play when switching icons, see [#animate(MFXFontIcon,MFXFontIcon)].
    public MFXIconWrapper setAnimationProvider(BiFunction<MFXFontIcon, MFXFontIcon, IconAnimation> animationProvider) {
        this.animationProvider = animationProvider;
        return this;
    }

    /// This can be used to convert one of the predefined animations in [AnimationPresets] to the [BiFunction]
    /// needed by [#setAnimationProvider(BiFunction)].
    public MFXIconWrapper setAnimationProvider(AnimationPresets preset) {
        this.animationProvider = (o, n) -> preset.animate(this, o, n);
        return this;
    }

    /// @return the [MFXRippleGenerator] instance for this wrapper, note that
    /// if the generator is not enabled, this will return `null` and also keep in mind that every time it is disabled
    /// and re-enabled, a new instance is created!
    public MFXRippleGenerator getRippleGenerator() {
        return rg;
    }
}
