# GitHub Action for code formatting using IntelliJ IDEA

name: IntelliJ Format
on:
  workflow_call: { }

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Cache IDEA
        uses: actions/cache@v3
        with:
          path: /home/runner/work/_temp/_github_workflow/idea-cache
          key: ${{ runner.os }}-idea-cache-v2

      # This is needed because the update changelogs script pushes a new commit therefore making this fail
      - name: Pull latest changes
        run: git pull origin ${{ github.ref_name }}

      - uses: notdevcody/intellij-format-action@main
        with:
          idea-version: '2025.3.3'
          include-glob: '*.java'
          style-settings-file: '.idea/codeStyles/Default.xml'
          push-type: 'commit'
          push-title: ':art: Reformat code'
          fail-on-changes: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
