name: Release on Maven

on:
  workflow_call: { }

# TODO setup npm to cleanup CSS
jobs:
  build-release:
    environment: MavenEnv
    runs-on: ubuntu-latest
    env:
      ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVEN_USERNAME }}
      ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVEN_PASSWORD }}
      ORG_GRADLE_PROJECT_signingInMemoryKeyId: ${{ secrets.GPG_ID }}
      ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.GPG_PASSWORD }}
      ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.GPG_KEY }}

    steps:
      - name: Clone repo
        uses: actions/checkout@v4
        with:
          # This is needed for the scripts
          fetch-depth: 0
          submodules: 'recursive'

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '25'

      - name: Give permissions to Gradle
        run: chmod +x gradlew

      - name: Release
        run: java -jar ./scripts/binaries/Release.jar
