name: 'Update Changelogs'

on:
  workflow_call: { }

jobs:
  update-changelogs:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v4
        with:
          # This is needed for the scripts
          fetch-depth: 0
          submodules: 'recursive'

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '25'

      - name: Run script
        run: java -jar ./scripts/binaries/UpdateChangelogs.jar --commit


